### ISSUE TITLE
When connected to TorBrowser I get this Info message non-stop. INFO, CBT Timeout rate 0.0

### ISSUE THREAD

**Issue by Baccount** [mikeperry-tor/vanguards#9] opened 2018-06-17 08:37 UTC
When connected to TorBrowser I get this Info message non-stop.
1. I edited TorBrowser torrc and added `ControlPort 9052`
2. Start the script using `./src/vanguards.py  --control_port 9052 --loglevel INFO --config /Users/"user"/Downloads/vanguards-master/vanguards-example.conf `
I get these errors when navigating to new sites in TorBrowser
```
INFO[Sun Jun 17 01:31:00 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:31:12 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:31:39 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:32:26 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:32:27 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:32:27 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:32:29 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:32:30 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:32:31 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
xINFO[Sun Jun 17 01:32:49 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:33:51 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:33:51 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
INFO[Sun Jun 17 01:33:53 2018]: CBT Timeout rate: 0.0; Our measured timeout rate: 0.0; Hidden service timeout rate: 0.0
```

**Comment by Baccount** [comment] 2018-06-19 23:49
Here is the config file I used to reproduce the bug.
[vanguards-example.conf.zip](https://github.com/mikeperry-tor/vanguards/files/2117271/vanguards-example.conf.zip)

**Comment by mikeperry-tor** [comment] 2018-07-20 02:15
This message is because cbtverify_enabled = True is set (or you were using an old checkout before it was disabled by default). If you don't want to see this, don't set that option.

As an aside, it's probably 0 because Tor did not gather enough circuit build time info yet.

**Comment by mikeperry-tor** [comment] 2018-07-20 02:46
I am going to close this since I think it is expected behavior. Reopen if I was wrong about the above.

**Closed by mikeperry-tor** 2018-07-20 02:46 UTC
